modLoader="javafml"
loaderVersion="[36,)"

license="All rights reserved"

[[mods]]

modId="megafix"

version="1.0"
displayName="MegaFix"
logoFile=""

credits=""
authors="Avibah"
description='''
A sidemod for use with Pixelmon 9.1.5

Simply fixes Mega Boss spawning for until 9.1.6 releases, where this will become obsolete.
'''

[[dependencies.megafix]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.megafix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.megafix]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.5,)"
    ordering="NONE"
    side="BOTH"