modLoader="javafml"
loaderVersion="[36,)"

license="All rights reserved"

[[mods]]

modId="megafix"

version="1.0"
displayName="MegaFix"
logoFile=""

credits=""
authors="Avibah"
description='''
A sidemod for use with Pixelmon 9.1.5

Simply fixes Mega Boss spawning for until 9.1.6 releases, where this will become obsolete.

Note for server owners: This mod works by enabling an event through the spawner responsible for spawning Mega Bosses. If you were implementing a receiver for the 'LegendarySpawnEvent.ChoosePlayer' event, you may want to add a check to ensure Mega Bosses don't set off your implementation where it expects Legendaries.
Similarly, if another mod you have expects this event to only be for Legendaries, there may be some odd behavior when the event is fired.
Also, due to the way this event influences Mega Boss spawn chances, the percentage for Mega Boss spawns are the same as Legendary spawns. If you wish to have these percentages still be different, consider adjusting the spawn ticks to match the frequency you desire.
'''

[[dependencies.megafix]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.megafix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.megafix]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.5,)"
    ordering="NONE"
    side="BOTH"